[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node server.js"

[environments.production]
variables = { NODE_ENV = "production" }

[environments.production.services.web]
